spring:
  application:
    name: mssc-brewery-gateway
  cloud:
    gateway:
      routes:
        - id: beer-service
          uri: lb://beer-service
          predicates:
            - Path=/api/v1/beer,/api/v1/beer/*
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/v1/customers,/api/v1/customers/**
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/api/v1/beer/*/inventory
eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
server:
  port: 9090