spring:
  application:
    name: mssc-brewery-gateway
  cloud:
    gateway:
      routes:
        - id: beer-service
          uri: http://localhost:8080
          predicates:
            - Path=/api/v1/beer,/api/v1/beer/*
        - id: order-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/customers,/api/v1/customers/**
        - id: inventory-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/beer/*/inventory
server:
  port: 9090