spring:
  application:
    name: mssc-beer-order-service
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
  jackson:
    default-property-inclusion: non_null
  h2:
    console:
      enabled: true
  artemis:
    broker-url: tcp://localhost:61616
    user: artemis
    password: artemis
server:
  port: 8081
app:
  brewery:
    beer-service-host: http://localhost:8080
logging:
  level:
    com.example.beerorderservice: debug
    org.apache.activemq: warn